{{- if ne .disableMetrics "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .AddonName }}-metrics
  namespace: {{ .AddonInstallNamespace }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
{{- end }}