apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hypershift-addon-metrics
  namespace: openshift-monitoring
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
    matchNames:
    - open-cluster-management-agent-addon
  selector:
    matchLabels:
      app: hypershift-addon-metrics